# This is a basic workflow to help you get started with Actions

name: OUCAutoUpdate

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  schedule:
    - cron: '10 16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  OUCAutoUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Setup python'
        uses: actions/setup-python@v1
        with:
          python-version : '3.7'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: 'OUCAutoUpdate'
        env:
          LOGINKEY: ${{ secrets.LOGINKEY }}
          SENDKEY: ${{ secrets.SENDKEY }}
          FORM_DATA: ${{ secrets.FORM_DATA }}
          FORM_DATA_TJ_HOME: ${{ secrets.FORM_DATA_TJ_HOME }}
        run: python OUCAutoUpdate.py
